version: '3.8'

services:
  db:
    image: bitnami/mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/bitnami/mysql/data
    tmpfs:
      - /var/lib/mysql

volumes:
  mysql_data:
