version: '3.9'

services:
  db:
    image: bitnami/mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: "admin"
      MYSQL_ROOT_PASSWORD: "toor"
      MYSQL_PASSWORD: "toor"
      MYSQL_DATABASE: "backend"
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/bitnami/mysql/data
    tmpfs:
      - /var/lib/mysql

  redis:
    image: redis
    command: redis-server --requirepass Redis2024!
    ports:
      - "6379:6379"

volumes:
  mysql_data:
